name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH & Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: your_server_ip  # 替换为你的服务器IP
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/flask-cicd-demo
            git fetch --all
            git reset --hard origin/main  # 强制同步代码
            /home/ubuntu/flask-cicd-demo/venv/bin/pip install -r requirements.txt
            sudo systemctl restart flaskapp
            sleep 5  # 等待服务启动
            curl -v http://localhost  # 打印详细响应
