name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH & Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: your_server_ip  # 替换为你的服务器IP
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/flask-cicd-demo
            git pull origin main
            sudo systemctl restart flaskapp
            curl -s http://localhost | grep -q "你的关键内容"  # 验证更新
